// このファイルは「AI 問い合わせ整理キット」の src/ からの写しです（中身は書き換えていません）。
// 直すときはキットの側を直してから、scripts/sync-gas-kits.mjs を走らせてください。
/**
 * 見本のメール 8 通と、その答え。鍵なしの「見本のメールで試す」と、テストで使う。
 * 会社・人名・電話・住所はすべて架空（電話は 03-0000-0000 帯、住所は「みなと市」）。
 * 8 通目は配信メール（List-Unsubscribe あり）で、Claude に送らず対象外になる見本。
 */

export const SAMPLE_EMAILS = [
  {
    id: "quote-01",
    from: "みなと 太郎 <taro@example.com>",
    subject: "会議室の内装工事の見積もりをお願いします",
    date: "2026-09-14T01:32:00Z",
    plainBody: "お世話になります。みなと商会 総務部の みなと 太郎 です。\n\n本社 3 階の会議室（約 40 ㎡）の内装工事について、見積もりをお願いできますでしょうか。\n希望は 10 月中の着工で、図面を添付します。\n9 月 30 日までにお見積もりをいただけると助かります。\n\nみなと商会 総務部 みなと 太郎\n電話 03-0000-0001",
    attachmentNames: ["会議室_図面.pdf"],
    headers: { listUnsubscribe: "", precedence: "", autoSubmitted: "" },
  },
  {
    id: "question-01",
    from: "さくら 花子 <hanako@example.com>",
    subject: "営業時間と駐車場について",
    date: "2026-09-14T02:05:00Z",
    plainBody: "はじめまして。土曜日も営業されていますか。\nまた、お店の近くに駐車場はありますでしょうか。\n来週の土曜日に伺いたいと考えています。",
    attachmentNames: [],
    headers: { listUnsubscribe: "", precedence: "", autoSubmitted: "" },
  },
  {
    id: "complaint-01",
    from: "ひかり工務店 田中 <tanaka@example.com>",
    subject: "納品が遅れています",
    date: "2026-09-14T03:10:00Z",
    plainBody: "9 月 10 日納品の予定だった品がまだ届いていません。\n現場が止まっており、大変困っています。\n本日中に状況を教えてください。\n\nひかり工務店 田中\n03-0000-0002",
    attachmentNames: [],
    headers: { listUnsubscribe: "", precedence: "", autoSubmitted: "" },
  },
  {
    id: "schedule-01",
    from: "あおば 次郎 <jiro@example.com>",
    subject: "9/18 の打ち合わせの時間変更",
    date: "2026-09-14T04:20:00Z",
    plainBody: "お世話になっております。あおば印刷の あおば です。\n9 月 18 日 14:00 からの打ち合わせを、16:00 に変更いただくことは可能でしょうか。\n難しければ 19 日の午前でも構いません。",
    attachmentNames: [],
    headers: { listUnsubscribe: "", precedence: "", autoSubmitted: "" },
  },
  {
    id: "billing-01",
    from: "経理 みなと不動産 <keiri@example.com>",
    subject: "8 月分の請求書について",
    date: "2026-09-14T05:00:00Z",
    plainBody: "8 月分の請求書（No. INV-2026-0801）の金額が、お見積もりと 5,500 円異なっております。\n内訳をご確認のうえ、訂正した請求書を再送いただけますでしょうか。\n支払期日が 9 月 20 日のため、お早めにお願いします。",
    attachmentNames: ["INV-2026-0801.pdf"],
    headers: { listUnsubscribe: "", precedence: "", autoSubmitted: "" },
  },
  {
    id: "sales-01",
    from: "営業部 <sales@example.com>",
    subject: "【ご提案】Web 集客を 3 倍にするサービスのご案内",
    date: "2026-09-14T06:00:00Z",
    plainBody: "突然のご連絡失礼いたします。\n弊社では Web 集客を支援するサービスを提供しております。\n15 分ほどオンラインでご説明の機会をいただけないでしょうか。",
    attachmentNames: [],
    headers: { listUnsubscribe: "", precedence: "", autoSubmitted: "" },
  },
  {
    id: "recruit-01",
    from: "山田 <yamada@example.com>",
    subject: "求人への応募について",
    date: "2026-09-14T07:15:00Z",
    plainBody: "求人サイトで事務スタッフの募集を拝見しました。\n応募を希望します。履歴書を添付しますので、ご確認ください。\n面接の日程は平日の午後であれば調整できます。",
    attachmentNames: ["履歴書.pdf"],
    headers: { listUnsubscribe: "", precedence: "", autoSubmitted: "" },
  },
  {
    id: "newsletter-01",
    from: "ニュースレター <newsletter@example.com>",
    subject: "今週のおすすめ情報",
    date: "2026-09-14T08:00:00Z",
    plainBody: "今週のおすすめ情報をお届けします。\n配信停止はこちら。",
    attachmentNames: [],
    headers: { listUnsubscribe: "<https://example.com/unsubscribe>", precedence: "bulk", autoSubmitted: "" },
  },
];

export const SAMPLE_ANSWERS = {
  "quote-01": {
    category: "見積もり依頼",
    urgency: "中",
    summary: "本社 3 階の会議室（約 40 ㎡）の内装工事の見積もり依頼。10 月中の着工希望、図面つき",
    request: "9 月 30 日までに見積書を送ること",
    deadline: "2026-09-30",
    person: { name: "みなと 太郎", company: "みなと商会", phone: "03-0000-0001" },
    replyDraft: "みなと 太郎 様\n\nお問い合わせありがとうございます。みなと商会 の 担当者 です。\n会議室の内装工事のお見積もりのご依頼を承りました。添付の図面を確認のうえ、9 月 30 日までにお見積もりをお送りできるよう進めます。金額と着工の時期は、確認のうえご連絡します。",
    needsHuman: false,
    confidence: 0.95,
    notes: "",
  },
  "question-01": {
    category: "質問",
    urgency: "低",
    summary: "土曜日の営業と近隣の駐車場の有無についての質問。来週の土曜日に来店希望",
    request: "営業日と駐車場の案内",
    deadline: null,
    person: { name: "さくら 花子", company: null, phone: null },
    replyDraft: "さくら 花子 様\n\nお問い合わせありがとうございます。みなと商会 の 担当者 です。\n営業日と駐車場については、確認のうえご連絡します。来週の土曜日のご来店を心よりお待ちしております。",
    needsHuman: false,
    confidence: 0.9,
    notes: "",
  },
  "complaint-01": {
    category: "クレーム",
    urgency: "高",
    summary: "9 月 10 日納品予定の品が未着で、現場が止まっているとの申し出。本日中の状況説明を求めている",
    request: "本日中に納品の状況を伝えること",
    deadline: "2026-09-14",
    person: { name: "田中", company: "ひかり工務店", phone: "03-0000-0002" },
    replyDraft: "田中 様\n\nご連絡ありがとうございます。みなと商会 の 担当者 です。\n納品が遅れており、ご迷惑をおかけして申し訳ございません。ただちに状況を確認し、本日中にご連絡します。",
    needsHuman: true,
    confidence: 0.93,
    notes: "現場が止まっているとのこと。電話での連絡が望ましい",
  },
  "schedule-01": {
    category: "予約や日程",
    urgency: "中",
    summary: "9 月 18 日 14:00 の打ち合わせを 16:00 へ変更したいとの相談。19 日午前も可",
    request: "打ち合わせの時間変更の可否の返事",
    deadline: "2026-09-18",
    person: { name: "あおば 次郎", company: "あおば印刷", phone: null },
    replyDraft: "あおば 次郎 様\n\nご連絡ありがとうございます。みなと商会 の 担当者 です。\n9 月 18 日の打ち合わせの時間変更のご相談を承りました。16:00 への変更が可能かどうか、確認のうえご連絡します。",
    needsHuman: false,
    confidence: 0.94,
    notes: "",
  },
  "billing-01": {
    category: "請求や支払い",
    urgency: "高",
    summary: "8 月分の請求書 INV-2026-0801 の金額が見積もりと 5,500 円異なるため、訂正版の再送を求めている。支払期日 9 月 20 日",
    request: "内訳を確認し、訂正した請求書を再送すること",
    deadline: "2026-09-20",
    person: { name: null, company: "みなと不動産", phone: null },
    replyDraft: "お問い合わせありがとうございます。みなと商会 の 担当者 です。\n8 月分の請求書の金額について、内訳を確認のうえご連絡します。支払期日を考慮し、お早めに対応いたします。",
    needsHuman: true,
    confidence: 0.9,
    notes: "金額の相違。経理の確認が要る",
  },
  "sales-01": {
    category: "営業や勧誘",
    urgency: "低",
    summary: "Web 集客支援サービスの売り込み。オンライン説明の打診",
    request: "サービス説明の機会を求めている",
    deadline: null,
    person: { name: null, company: null, phone: null },
    replyDraft: "ご案内ありがとうございます。今回は見送らせていただきます。",
    needsHuman: false,
    confidence: 0.97,
    notes: "",
  },
  "recruit-01": {
    category: "採用",
    urgency: "中",
    summary: "事務スタッフの求人への応募。履歴書つき。面接は平日午後で調整可",
    request: "応募の受付と面接日程の連絡",
    deadline: null,
    person: { name: "山田", company: null, phone: null },
    replyDraft: "山田 様\n\nご応募ありがとうございます。みなと商会 の 担当者 です。\n履歴書を拝受しました。内容を確認のうえ、面接の日程についてあらためてご連絡します。",
    needsHuman: false,
    confidence: 0.92,
    notes: "",
  },
};
