// このファイルは、SaaS スターター キットからの写しです。
// 直すときはキットの側を直してから、scripts/sync-saas-starter.mjs を走らせてください。

/**
 * 法務の文面（素のテキスト）です。キットの legal/*.txt を、そのまま文字列にしたものです。
 * キットの側はファイルから読みますが、ブラウザの中だけで動く見本は読みに行けないので、
 * 写すときに 1 枚の TypeScript へ焼き直しています。
 */
export const LEGAL_TEXT: Readonly<Record<string, string>> = {
  "tokushoho.ja": "# ─────────────────────────────────────────────────────────\n# このファイルは、特定商取引法に基づく表記の「ひな形」です。\n# そのままお使いいただけることを保証するものではありません。\n# 公開なさる前に、お客さまの事業の内容に合わせて書き換えのうえ、\n# 弁護士など専門家のご確認をお願いいたします。\n#\n# {{ }} の値は legal.config.ts にあります。空のままにすると、\n# 画面に「（未記入）」と出て、ページの上に帯が立ちます。\n# この行のように # ではじまる行は、覚え書きです。画面には出ません。\n# ─────────────────────────────────────────────────────────\n\n## 販売事業者\n{{sellerName}}\n\n## 運営統括責任者\n{{representative}}\n\n## 所在地\n{{address}}\n\n## 電話番号\n{{phone}}\nお電話の受付時間は、{{contactHours}}です。\n\n## メールアドレス\n{{email}}\n\n## 販売価格\n{{priceNote}}\n\n## 商品代金以外の必要料金\n{{extraCharges}}\n\n## お支払い方法\n{{paymentMethods}}\n\n## お支払いの時期\n{{paymentTiming}}\n\n## サービスのご提供時期\n{{deliveryTiming}}\n\n## 返品・キャンセルについて\n{{refundPolicy}}\n\n## 動作環境\nインターネットにつながるパソコン、またはスマートフォンのブラウザでご利用いただけます。ブラウザは、更新のお済みの新しい版をおすすめいたします。\nCookie を無効に設定なさっている場合は、ログインができません。\n",
  "tokushoho.en": "# ─────────────────────────────────────────────────────────\n# This file is a template for the notice required by the Japanese\n# Act on Specified Commercial Transactions. It is not guaranteed to be\n# usable as it stands. Before you publish it, rewrite it to match your\n# own business and have a lawyer review it.\n#\n# The Japanese file is the one that counts. Only the seller, the\n# representative, the address, the phone number and the email address are\n# filled in from legal.config.ts, and they appear exactly as you wrote\n# them there. The rest is written out in English below, so keep it in step\n# with tokushoho.ja.txt by hand whenever you change one of them.\n# Lines that start with # are notes for you. They are never shown on the page.\n# ─────────────────────────────────────────────────────────\n\nThis is a summary in English of the notice required by the Japanese Act on Specified Commercial Transactions.\n\n## Seller\n{{sellerName}}\n\n## Managing representative\n{{representative}}\n\n## Address\n{{address}}\n\n## Phone\n{{phone}}\nWe take calls on weekdays, from 10 to 17, Japan time, except on public holidays and over the new year.\n\n## Email\n{{email}}\n\n## Price\nEvery plan and its price are listed under Pricing on our home page. Prices include Japanese consumption tax.\n\n## Fees on top of the price\nYou cover the cost of your own internet connection.\n\n## How you pay\nWe accept credit cards. Stripe processes the payment.\n\n## When you pay\nYou pay for your first month as soon as you finish subscribing. The subscription then renews by itself every month, on the same day and for the same amount, until you cancel it.\n\n## When the service starts\nYou can use your plan as soon as we confirm the payment.\n\n## Cancellations and refunds\nYou can cancel at any time from the billing screen. After you cancel, your plan stays available until the end of the period you have already paid for. Because of the nature of the service, we do not refund fees you have paid, and we do not work out part-month amounts.\n\n## What you need to use the service\nAn up-to-date browser on a computer or a phone, and an internet connection. You cannot sign in with cookies turned off.\n\nThis English text is provided for convenience. Where it differs from the Japanese, the Japanese text prevails.\n",
};
